build.mill

The name `LazyList` was introduced only in later version of Scala collections to be distinct from `Stream` which had a different API, but provided the same functionality. `Stream` was a much better name: shorter, and a single word. Since the original `Stream` is long deprecated, `LazyList` should be promoted into its namespace.

Rename `LazyList` to `Stream`

---

build.mill

This PR makes the necessary changes to get the Superlunary example working again.

Fix Superlunary

---

build.mill

This fixes the compile errors with Tarantula, and tidies up its imports.

Fix Tarantula

---

build.mill

This is a huge set of changes to mostly replace `Decoder` (from Spectacular) with the generalized `Decodable in Text` (from Anticipation).
One problem with defining `Decodable` in such a base module is that it becomes impossible to define a few types like, `Int is Decodable in Text`, in the companion object of either the typeclass (`Decodable`) or its parameter (`Int`). Obviously the parameter here is a primitive type, so we don't have access to its companion. But at the time `Decodable`'s companion object must be defined, we don't have Contingency for defining `Tactic`s and `raise` and we don't have the exception, `NumberError`.
Currently we work around this by keeping the companion object `Decoder` in Spectacular, and importing `Decoder.int` and others directly from it. This is far from …

Use `Decodable in Text` instead of `Decoder`

---

lib/ambience/src/core/ambience.Xdg.scala
lib/cellulose/src/core/cellulose.Codl.scala
lib/cellulose/src/test/cellulose.Tests.scala
lib/gossamer/src/core/gossamer.Decimalizer.scala
lib/telekinesis/src/core/telekinesis.Http.scala
sample/tube/src/core/tube.scala

I'm not sure how these long lines slipped through the net last time I checked, but they've now been eliminated.

Eliminate remaining long lines

---

lib/acyclicity/src/core/acyclicity.Dag.scala
lib/caesura/src/core/caesura.Row.scala
lib/cataclysm/src/core/cataclysm-core.scala
lib/charisma/src/core/charisma.ChemicalFormula.scala
lib/charisma/src/core/charisma.Formulable.scala
lib/charisma/src/core/charisma.Molecular.scala
lib/contingency/src/core/contingency.Foci.scala
lib/denominative/.github/readme.md
lib/denominative/doc/basics.md
lib/denominative/src/core/denominative.Denominative.scala
lib/digression/src/core/digression.StackTrace.scala
lib/galilei/src/core/galilei-core.scala
lib/gossamer/src/core/gossamer.Joinable.scala
lib/guillotine/src/core/guillotine.Sh.scala
lib/hieroglyph/src/core/hieroglyph-core.scala
lib/iridescence/src/core/iridescence.Rgb24Opaque.scala
lib/jacinta/src/core/jacinta.Json.scala
lib/probably/src/core/probably.Report.scala
lib/punctuation/src/ansi/punctuation.TextConverter.scala
lib/punctuation/src/html/punctuation.HtmlConverter.scala
lib/rudiments/src/core/rudiments-core.scala
lib/rudiments/src/core/rudiments.Rudiments.scala
lib/vicarious/src/core/vicarious.Vicarious.scala
lib/wisteria/.github/readme.md
lib/wisteria/doc/basics.md

This implements and adopts `fuse` as a lightweight, inline alternative to `foldLeft`, implemented with a `while` loop.

Switch to using `fuse` over `foldLeft` where possible

---

lib/anamnesis/src/core/anamnesis-core.scala
lib/anamnesis/src/core/anamnesis.DataError.scala
lib/anamnesis/src/core/anamnesis.Database.scala
lib/anamnesis/src/core/soundness+anamnesis-core.scala

Further improvements to Anamnesis

Rename `DbError` to `DataError` and export it

---

lib/geodesy/src/core/geodesy-core.scala
lib/geodesy/src/core/geodesy.CardinalWind.scala
lib/geodesy/src/core/geodesy.IntercardinalWind.scala

Provide unicode textual representations of compass points.

Show compass directions as arrows

---

build.mill
lib/turbulence/src/test/turbulence.Tests.scala

Tests for Turbulence were not compiling. These have now been fixed or commented-out where they're no longer appropriate.

Fix the Turbulence tests

---

build.mill
lib/mosquito/src/test/mosquito.Tests.scala

This makes the necessary changes to ensure that Mosquito's tests now compile, run and pass.

Fix tests for Mosquito

---

lib/rudiments/src/core/rudiments-core.scala
lib/rudiments/src/core/soundness+rudiments-core.scala
lib/symbolism/src/core/symbolism.Divisible.scala

Added an implementation of `standardDeviation` and simplified the implementations of other aggregate functions.

Better `variance`, `mean` and `standardDeviation` support

---

lib/gesticulate/src/core/gesticulate.Multipart.scala
lib/probably/src/core/probably-core.scala
lib/probably/src/core/soundness+probably-core.scala
lib/zephyrine/src/core/zephyrine.Conduit.scala
lib/zephyrine/src/test/zephyrine.Tests.scala

`Conduit` had a serious bug where captured data would be duplicated. This is now fixed.

Fix and test `Conduit`

---

lib/mercator/src/core/mercator.Identity.scala
lib/wisteria/src/test/wisteria.Tests.scala

Now that we have better support for compiletime tests from Probably and Larceny, I'm starting work on tidying up Wisteria's tests. This will make it possible to work on improving Wisteria.

Start using Probably for Wisteria tests

---

lib/panopticon/src/test/panopticon.Tests.scala

Improve Panopticon tests

---

build.mill
lib/anticipation/src/text/anticipation.Anticipation.scala
lib/hieroglyph/src/core/hieroglyph-core.scala
lib/hieroglyph/src/core/hieroglyph.Unicode.scala
lib/satirical/src/core/satirical.Wit.scala
lib/satirical/src/test/satirical.Tests.scala
lib/zephyrine/src/core/zephyrine.Conduit.scala

This makes use of Unicode data to communicate (in a `Message`) a character's name. Also includes the character itself, if and only if it is printable.

Char name printing

---

lib/cellulose/src/core/cellulose.CodlDoc.scala
lib/cellulose/src/core/cellulose.CodlNode.scala
lib/chiaroscuro/src/core/chiaroscuro-core.scala
lib/chiaroscuro/src/core/chiaroscuro.Contrastable.scala
lib/chiaroscuro/src/core/chiaroscuro.Decomposable.scala
lib/chiaroscuro/src/core/chiaroscuro.Decomposition.scala
lib/chiaroscuro/src/core/chiaroscuro.Juxtaposition.scala
lib/chiaroscuro/src/core/soundness+chiaroscuro-core.scala
lib/chiaroscuro/src/test/chiaroscuro.Tests.scala
lib/denominative/src/core/denominative-core.scala
lib/denominative/src/core/soundness+denominative-core.scala
lib/escapade/src/core/escapade.Escapade.scala
lib/prepositional/src/core/prepositional-core.scala
lib/probably/src/core/probably-core.scala
lib/probably/src/core/probably.Benchmark.scala
lib/probably/src/core/probably.Harness.scala
lib/probably/src/core/probably.Probably.scala
lib/probably/src/core/probably.Report.scala
lib/probably/src/core/probably.Verdict.scala
lib/probably/src/core/soundness+probably-core.scala
lib/rudiments/src/core/rudiments-core.scala
lib/rudiments/src/core/soundness+rudiments-core.scala
lib/spectacular/src/core/soundness+spectacular-core.scala
lib/spectacular/src/core/spectacular.Inspectable.scala
lib/zephyrine/src/core/zephyrine.Conduit.scala

This reinstates the output in Probably showing a breakdown of differences between different values.

Improvements to output in Probably

---

lib/aviation/src/core/aviation.Aviation.scala
lib/aviation/src/core/aviation.Timestamp.scala

Provides a `Showable` instance for `Timestamp`s.

Make timestamps showable

---

lib/aviation/src/core/aviation-core.scala
lib/aviation/src/core/aviation.Aviation.scala
lib/aviation/src/core/aviation.DateNumerics.scala
lib/aviation/src/core/aviation.DateSeparation.scala
lib/aviation/src/core/aviation.Endianness.scala
lib/aviation/src/core/aviation.Timestamp.scala
lib/aviation/src/core/aviation.YearFormat.scala
lib/aviation/src/core/soundness+aviation-core.scala

This extends the previous pull request to provide more flexible numerical date formatting.

Showable timestamps

---

lib/aviation/src/core/aviation.Denomination.scala
lib/aviation/src/core/aviation.DiurnalTimespan.scala
lib/aviation/src/core/aviation.FixedDuration.scala
lib/aviation/src/core/aviation.TimeSystem.scala
lib/satirical/src/core/satirical.Wit.scala
lib/satirical/src/test/satirical.Tests.scala
lib/zephyrine/src/test/zephyrine.Tests.scala

Several new files were created without including the header files. These have been added using the automatic script.

Add some missing source file headers

---

lib/chiaroscuro/src/core/chiaroscuro.Contrastable.scala
lib/chiaroscuro/src/core/chiaroscuro.Juxtaposition.scala
lib/probably/src/core/probably.Probably.scala

Further minor enhancements to text comparison.

Some tweaks to text comparison

---

Makefile
build.mill
lib/abacist/src/test/abacist.Tests.scala
lib/caesura/src/test/caesura.Tests.scala
lib/gesticulate/src/test/gesticulate.Tests.scala
lib/inimitable/src/test/inimitable.Tests.scala
lib/jacinta/src/test/jacinta.Tests.scala
lib/kaleidoscope/src/test/kaleidoscope.Tests.scala
lib/metamorphose/src/test/metamorphose.Tests.scala
lib/nomenclature/src/test/nomenclature.Tests.scala
lib/panopticon/src/test/panopticon.Tests.scala
lib/punctuation/src/test/punctuation.Tests.scala
lib/telekinesis/src/test/telekinesis.Tests.scala

This is work-in-progress to run the tests for each module as part of the Soundness build.

Run all tests as part of the build

---

lib/legerdemain/src/core/legerdemain.Formulable.scala
lib/telekinesis/src/core/telekinesis-core.scala
lib/telekinesis/src/core/telekinesis-core2.scala
sample/tube/src/core/tube.scala

A few unused imports remained, which have been removed in this PR.

Eliminate some unused imports

---

lib/abacist/src/core/abacist.Abacist2.scala
lib/fulminate/src/core/fulminate.Message.scala
lib/honeycomb/src/core/honeycomb-core.scala
lib/honeycomb/src/core/honeycomb.Renderable.scala
lib/legerdemain/src/core/legerdemain-core.scala
lib/legerdemain/src/core/legerdemain.Autocomplete.scala
lib/legerdemain/src/core/legerdemain.Checkbox.scala
lib/legerdemain/src/core/legerdemain.Elicitable.scala
lib/legerdemain/src/core/legerdemain.Field.scala
lib/legerdemain/src/core/legerdemain.Formulable.scala
lib/legerdemain/src/core/legerdemain.Formulation.scala
lib/legerdemain/src/core/legerdemain.RadioGroup.scala
lib/legerdemain/src/core/legerdemain.Selection.scala
lib/legerdemain/src/core/soundness+legerdemain-core.scala
lib/rudiments/src/core/rudiments-core.scala
lib/rudiments/src/core/soundness+rudiments-core.scala
lib/superlunary/src/test/superlunary.Tests.scala
lib/telekinesis/src/core/soundness+telekinesis-core.scala
lib/telekinesis/src/core/telekinesis-core2.scala

This generalizes the code for rendering the HTML markup surrounding a widget, including details like text labels and validation messages.

Improvements to Legerdemain form rendering

---

lib/contingency/src/core/contingency-core.scala
lib/contingency/src/core/contingency.Contingency.scala
lib/contingency/src/core/contingency.Pointer.scala
lib/contingency/src/core/contingency.Validation.scala
lib/contingency/src/core/soundness+contingency-core.scala
lib/honeycomb/src/core/soundness+honeycomb-core.scala
lib/legerdemain/src/core/legerdemain-core.scala
lib/legerdemain/src/core/legerdemain.Elicitable.scala
lib/legerdemain/src/core/legerdemain.Formulaic.scala
lib/legerdemain/src/core/legerdemain.Query.scala
lib/legerdemain/src/core/soundness+legerdemain-core.scala
lib/telekinesis/src/core/telekinesis-core2.scala

This finally achieves a decent API for constructing web forms and handling validation errors.

Improvements to Legerdemain

---

lib/distillate/src/core/distillate.Distillate.scala
lib/distillate/src/core/distillate.Enumerable.scala
lib/distillate/src/core/distillate.Requirable.scala
lib/legerdemain/src/core/legerdemain.Combobox.scala
lib/legerdemain/src/core/legerdemain.Formulaic.scala
lib/legerdemain/src/core/soundness+legerdemain-core.scala
lib/telekinesis/src/core/telekinesis-core2.scala

This includes several improvements to orchestrating a web form, including a failed attempt to identify which fields are required. There's hope yet that it might work.

Various improvements to form orchestration

---

build.mill
lib/escritoire/src/core/escritoire.Column.scala
lib/hyperbole/src/core/hyperbole.Hyperbole.scala
lib/mandible/src/core/mandible-core.scala
lib/mandible/src/core/mandible.Bytecode.scala
lib/mandible/src/core/mandible.Classfile.scala
lib/mandible/src/core/mandible.Mandible.scala
lib/mandible/src/test/mandible.Tests.scala

This introduces an analysis tool for Scala bytecode.

Initial implementation of Mandible

---

lib/parasite/src/core/parasite.GarbageCollection.scala

Include details of how much memory is reclaimed from garbage collection.

Provide more GC detail

---

lib/parasite/src/core/parasite-core.scala
lib/parasite/src/core/parasite.GarbageCollection.scala
lib/parasite/src/core/parasite.Timeout.scala

This provides a `Timeout` class for running a task after a period of inactivity.

Implement `Timeout`

---

etc/oldbranches
lib/digression/src/core/digression.StackTrace.scala
lib/galilei/src/core/galilei-core.scala
lib/octogenarian/src/core/octogenarian.GitRepo.scala
lib/probably/src/cli/probably.Suite.scala

Reduces the output slightly. Also include `oldbranches` script.

Clean up some spurious `println`s

---

build.mill
lib/perihelion/src/core/perihelion.Websocket.scala

Recursive publishing appeared to be duplicating publish operations for modules that appeared more than once in the tree. This his been fixed by publishing an explicit list of modules.

Try to fix publishing locally

---

build.mill
lib/ulysses/src/test/ulysses.Tests.scala
src/test/soundness.Tests.scala

Fixes the tests for Ulysses and adds them to the test suite.

Add Ulysses tests

---

lib/hypotenuse/src/core/soundness+hypotenuse-core.scala
lib/monotonous/src/core/monotonous.Serializable.scala
lib/monotonous/src/test/monotonous.Tests.scala
src/test/soundness.Tests.scala

This fixes the Monotonous and Enigmatic tests.

Fix monotonous padding

---

lib/baroque/src/core/baroque.Complex.scala
lib/baroque/src/test/baroque.Tests.scala
lib/quantitative/src/core/quantitative-core.scala
src/test/soundness.Tests.scala

And include them in Soundness tests.

Fix Baroque tests

---

lib/hypotenuse/src/core/hypotenuse.Hypotenuse.scala
lib/iridescence/src/test/iridescence.Tests.scala

This fixes some of the `Orderable` implementations in Hypotenuse, and reinstates some disabled tests for Iridescence.

Some miscellaneous fixes

---

lib/aviation/src/core/anticipation+aviation-core.scala
lib/aviation/src/core/aviation.Aviation2.scala
lib/cataclysm/src/core/cataclysm.PropertyDef.scala
lib/quantitative/src/core/quantitative-core.scala
lib/quantitative/src/core/quantitative.Expressible.scala
lib/quantitative/src/core/quantitative.Normalizable.scala
lib/quantitative/src/core/quantitative.Quantitative.scala
lib/quantitative/src/core/quantitative.Quantitative2.scala
lib/quantitative/src/core/soundness+quantitative-core.scala
lib/quantitative/src/test/quantitative.Tests.scala

Improved support for different units of duration. Also improved division of `Quantity`s.

Improve generalization of durations

---

lib/telekinesis/src/core/telekinesis.Receivable.scala

When `receive`ing a value of a certain type, we were just getting the HTTP response body regardless of the status. That often caused unexpected failures because the body was either missing or some kind of error message. This change raises an `HttpError` in the cases where it's not a successful status.

Ensure that `HttpError` is required when `receive`ing types

---

lib/harlequin/src/core/harlequin.SourceCode.scala

Soft modifiers like `inline`, `open`, `transparent` and `infix` were not being highlighted as modifiers because that status is determined by whether they precede a keyword or hard modifier. We now post-process the stream of tokens to highlight soft modifiers.

Make sure soft modifiers are highlighted in Scala source

---

lib/dissonance/src/core/dissonance.Evolution.scala
lib/harlequin/src/core/harlequin.SourceCode.scala

There was an issue where some source tokens were getting lost during an evolution. This is fixed now.

Fix an issue with evolutions

---

lib/contingency/.github/readme.md
lib/harlequin/src/core/harlequin.SourceCode.scala
lib/probably/src/core/probably.Probably.scala
lib/proscenium/src/core/proscenium-core.scala
lib/proscenium/src/core/soundness+proscenium-core.scala
lib/rudiments/src/core/rudiments-core.scala
lib/sedentary/src/core/sedentary-core.scala

This is another fix for "softening" of keywords, which stopped working again in some cases.

Whitespace changes and fix "softening" in Harlequin

---

build.mill

Bitumen and Embarcadero aren't ready yet, so don't try to build them.

Do not build broken modules

---

etc/publish

Activate publish-on-tag, hopefully.

Make publish-on-tag actually publish

---

lib/hallucination/src/core/hallucination.Raster.scala
lib/hallucination/src/test/hallucination.Tests.scala

Allow images to be converted from one format to another.

Support image conversion

---

lib/hallucination/src/core/hallucination.Raster.scala

Adds some new methods to `Raster`. We now have `flipX`, `flipY`, `rotate` and `crop`.

Hallucination improvements

---

lib/aviation/src/core/aviation-core.scala
lib/aviation/src/core/aviation.Aviation2.scala
lib/aviation/src/test/aviation.Tests.scala
lib/probably/src/core/probably.Report.scala

This is a rewrite of the ISO 8601 timestamp parser, which should now support a wider variety of different variations on the format.

Faster, more general ISO 8601 parser

---

.github/workflows/publish.yml

Adapt the "publish-on-tag" script to use GitHub deployments.

Use deployments

---

.github/workflows/publish.yml

This includes tweaks to the `publish.yml` script.

Another attempt to fix the publishing workflow
