build.mill

There were a few failing tests in Kaleidoscope. These are now fixed, apart from those that require Larceny (due to #27).

Fix various errors in Kaleidoscope so that the tests pass

---

.gitmodules
build.mill

A foundational set of imports from the standard library has always been included in Rudiments, since it was a convenient place for them. But projects _before_ Rudiments could not make use of them, and it became a less and less natural home for them.
They have been moved out into a new module, Proscenium. This PR adds Proscenium, removes the exports from Rudiments, and updates every other import to accommodate this change.

Use proscenium

---

build.mill

We need to ensure that all the test submodules depend on the other submodules in the same module. This happens automatically by projects that are transitive dependencies of `probably.cli`, but for downstream projects, we need to specify it manually.

Ensure all test modules have necessary dependencies

---

build.mill

The way to send HTTP requests with Telekinesis has changed. There are now two methods on any URL type (for which a `Fetchable` instance exists) for sending requests:
- `submit` for requests which take a payload
-  `fetch` for requests without payloads
In general, they are invoked with:
```scala
url.fetch(headers*)
```
or
```scala
url.submit(headers*)(payload)
```
The type of `payload` is any type for which a `Postable` instance exists, and should include all useful types like `Json` and `Text`.
The `headers` fields include,
- optionally, an HTTP request method like `Http.Post`, `Http.Head` or `Http.Get`; if this is not specified, it defaults to `Http.Post` for `submit` and `Http.Get` for `fetch`
- varargs of camel-case named HTTP headers, with appropriate types, such as `accept = …

Improvements to Telekinesis request API

---

build.mill

This adds a new format for log output customised for Google Cloud Platform, which consumes logs in JSON. To use it,
```scala
import eucalyptus.logFormats.googleCloudPlatform
```

Add GCP logging

---

build.mill

`Term`s, `Expr[?]`s, `Type[?]`s and `TypeRepr`s can now be embedded in `Message`s. This should obviate several `toString` and `show` invocations in macro implementations.

Support embedding of macro types in `Message`s

---

build.mill

There was an error in the build file which made the Abacist tests run without Larceny. That's now fixed, and some `println` output has been removed from the tests.
However, the two compiletime tests are not producing the right results. This is a problem with testing, in particular Larceny, rather than Abacist.

Run the Abacist tests

---

build.mill

This adds support for publishing, which has been tested locally. The publish version comes from the most recent `git` tag. We might need to refine the exact workflow if we publish-on-tag.

Support for publishing (locally, at least)

---

build.mill
sample/tube/src/core/tube.scala

Some lesser-used modules (typically from non-core modules) were not noticed. These have now been fixed.

Fix compile errors in lesser-used modules

---

sample/tube/src/core/tube.scala

`TcpError`s may be raised for a number of reasons. Until now, the exact cause was not discerned. An attempt is now made to determine, based on the type of exception thrown and its message, some detail on the cause. It's still possible to improve upon this with more detail, but we should test this before trying more precise diagnosis.

Better diagnosis of TCP errors

---

.gitmodules
build.mill

In order to communicate with Docker using its REST API, HTTP requests must be sent to the UNIX domain socket, `/var/run/docker.sock`. Other services may use similar methods of interaction.
Telekinesis now supports sending HTTP requests using alternative "`HttpClient`s", including to UNIX domain socket endpoints.

Support for UNIX domain sockets

---

lib/fulminate/src/core/fulminate.Communicable.scala
lib/scintillate/src/server/scintillate.RequestParam.scala
lib/scintillate/src/server/soundness+scintillate-server.scala
lib/telekinesis/src/core/soundness+telekinesis-core.scala
lib/telekinesis/src/core/telekinesis.Parameter.scala
lib/telekinesis/src/core/telekinesis.Query.scala
lib/telekinesis/src/core/telekinesis.Telekinesis.scala
lib/telekinesis/src/test/telekinesis.Tests.scala

The `Query` type represents a set of key/value pairs for sending in an HTTP post. You can construct one with,
```scala
Query(key1 = t"some value", key2 = 42)
```
provided `key1` and `key2` have (erased) contextual `Parameter` instances, with appropriate types, and provided those types are `Encodable in Text`.
For the above example, you would need, for example,
```scala
erased given ("key1" is Parameter of Text) = ###
erased given ("key2" is Parameter of Int) = ###
```

Support typed HTTP queries

---

lib/coaxial/src/core/coaxial-core.scala
lib/coaxial/src/core/soundness+coaxial-core.scala
lib/telekinesis/src/core/soundness+telekinesis-core.scala
lib/telekinesis/src/core/telekinesis.HttpClient.scala
lib/telekinesis/src/core/telekinesis.Query.scala

This avoids a warning in user code about certain implicit values conflicting after priorities are changed in Scala 3.7.

Avoid the warning about ambiguous contextual values in Scala 3.7

---

lib/geodesy/src/core/geodesy.Geodesy.scala
lib/geodesy/src/core/geodesy.Geolocation.scala

Some systems use integer values of millidegrees to represent locations. This is now supported with a new `apply` method on `Location`.

Allow construction of `Location` in millidegrees

---

lib/merino/src/core/merino.JsonAst.scala

When parsing JSON numbers, either `Long.parseLong` or `Double.parseDouble` were used. The choice was determined by the presence or absence of a decimal point. But a number such as `4E+2`, although an integer, and without a decimal point, cannot be parsed by `Long.parseLong`. So now we note the presence of `E` or `e` and use `parseDouble` instead.

Avoid parsing error in JSON numbers

---

lib/geodesy/src/core/geodesy.Geodesy.scala

The new `Location.apply` method interpreted a latitude and longitude integer as millidegrees. But actually, by convention, they're _microdegrees_. So the result is a factor of 1000 off, or for most inputs, is limited by the range of values.

Interpret integers as microdegrees, not millidegrees

---

lib/quantitative/src/core/quantitative.Quantitative.scala
lib/quantitative/src/test/quantitative.Tests.scala
lib/quantitative/src/units/quantitative.unitDefinitions.scala

When auto-converting a `Double` to a `Quantity`, we were adapting the `Quantity`'s arguments to be whatever we wanted. But we only want to do the conversion from a double to a unitless `Quantity`, i.e. a `Quantity[Measure]`. The contextual instances of `Conversion[Double, Quantity[UnitsType]]` have been constrained now.

Safely convert `Double`s to `Quantity`s without breaking units

---

lib/abacist/src/test/abacist.Tests.scala
lib/fulminate/src/core/fulminate.Message.scala
lib/quantitative/src/core/quantitative.Dimension.scala
lib/quantitative/src/core/quantitative.PhysicalQuantity.scala
lib/quantitative/src/core/quantitative.PrincipalUnit.scala
lib/quantitative/src/core/quantitative.Units.scala
lib/quantitative/src/core/soundness+quantitative-core.scala
lib/quantitative/src/test/quantitative.Tests.scala
lib/quantitative/src/units/quantitative.Chains.scala
lib/quantitative/src/units/quantitative.Feet.scala
lib/quantitative/src/units/quantitative.Furlongs.scala
lib/quantitative/src/units/quantitative.Inches.scala
lib/quantitative/src/units/quantitative.Lightyears.scala
lib/quantitative/src/units/quantitative.Miles.scala
lib/quantitative/src/units/quantitative.NauticalMiles.scala
lib/quantitative/src/units/quantitative.Picas.scala
lib/quantitative/src/units/quantitative.Points.scala
lib/quantitative/src/units/quantitative.Yards.scala
lib/savagery/src/core/savagery.Svg.scala

`Length` in Quantitative conflicted with `Length` in Cataclysm. Ultimately, Cataclysm may be thoroughly refactored, but for now it's sufficient to rename `Length` to `Distance` in Quantitative.

Renamed `Length` in Quantitative to `Distance` to avoid conflict with Cataclysm

---

lib/quantitative/src/core/quantitative.PrincipalUnit.scala
lib/quantitative/src/core/quantitative.UnitName.scala
lib/quantitative/src/core/quantitative.Units.scala
lib/quantitative/src/core/soundness+quantitative-core.scala
lib/quantitative/src/units/quantitative.ArcMinutes.scala
lib/quantitative/src/units/quantitative.ArcSeconds.scala
lib/quantitative/src/units/quantitative.Degrees.scala
lib/quantitative/src/units/quantitative.unitDefinitions.scala
lib/quantitative/src/units/soundness+quantitative-units.scala

`Radians` were defined in both Geodesy and Quantitative, leading to a conflict when both were exported to `soundness`. This removes the definition in Quantitative, since radians are not "units" in the same sense as other quantities have units.

Remove `Radians` in Quantitative

---

lib/ambience/src/core/ambience.Environment.scala
lib/aviation/src/core/aviation.Aviation.scala
lib/aviation/src/core/aviation.RomanCalendar.scala
lib/aviation/src/core/aviation.Timezone.scala
lib/contingency/src/core/contingency-core.scala
lib/digression/src/core/digression.Fqcn.scala
lib/dissonance/src/core/dissonance.Diff.scala
lib/distillate/src/core/distillate.Decodable.scala
lib/escritoire/src/core/escritoire-core.scala
lib/galilei/src/core/galilei-core.scala
lib/gesticulate/src/core/gesticulate.Media.scala
lib/hieroglyph/src/core/hieroglyph-core.scala
lib/hypotenuse/src/core/hypotenuse-core.scala
lib/inimitable/src/core/inimitable.Uuid.scala
lib/monotonous/src/core/monotonous.Alphabet.scala
lib/nettlesome/src/core/nettlesome.EmailAddress.scala
lib/nettlesome/src/core/nettlesome.Nettlesome.scala
lib/nettlesome/src/url/nettlesome.Authority.scala
lib/octogenarian/src/core/octogenarian.Octogenarian.scala
lib/punctuation/src/core/punctuation.Markdown.scala
lib/telekinesis/src/core/telekinesis.Http.scala
lib/turbulence/src/core/turbulence.Readable.scala
lib/wisteria/src/core/wisteria.SumDerivationMethods.scala
lib/xylophone/src/core/xylophone.XmlDecoder.scala

Replaces every occurrence of `raise(error, ersatz)` with `raise(error) yet ersatz`. This obviates the two-parameter variant of `raise.

Eliminate the unnecessary two-parameter variant of `raise`

---

lib/larceny/src/plugin/larceny.LarcenyTransformer.scala
lib/larceny/src/plugin/larceny.Subcompiler.scala

Larceny was sometimes failing to capture certain errors, and code which would clearly not compile was appearing to have no errors. That turned out to have two causes.
Firstly, the error position being reported was not the "primary" error position in the problematic file. The `Diagnostic` from the compiler needed to be "dereferenced" to reach the outermost error.
Secondly, subcompilations were being done with different settings from those used for the main compilation. These caused errors elsewhere in the file under compilation which shadowed the desired error.
Both these issues are now fixed.

Fix a couple of problems with Larceny

---

lib/parasite/src/core/parasite.Promise.scala
lib/parasite/src/test/parasite.Tests.scala

A misuse of `updateAndGet` when `getAndUpdate` should have been used was causing `Promise`s to simply not work. This is been fixed, but much more testing is required.

Fix a serious breakage in `Promise` fulfillment

---

build.mill
lib/austronesian/src/core/austronesian-core.JavaError.scala
lib/austronesian/src/core/austronesian-core.scala
lib/austronesian/src/core/austronesian.Austronesian.scala
lib/austronesian/src/core/austronesian.Austronesian2.scala
lib/austronesian/src/core/austronesian.StdlibError.scala
lib/austronesian/src/test/austronesian.Tests.scala
lib/vacuous/src/core/soundness+vacuous-core.scala
lib/vacuous/src/core/vacuous.Optional.scala

Sometimes we need datatypes to be portable across domains with subtly different representations, even within the same JVM. A particular example regards passing data between different versions of the same code running in different classloaders, for example, when invoking a different version of the same library or compiled for a different version of Scala.
Austronesian provides a means of conversion of primitives, collections, products and sum types to the "lowest common denominator" representation: JVM primitives.

Introduce Austronesian

---

lib/anamnesis/src/core/anamnesis-core.scala
lib/anamnesis/src/core/anamnesis.Anamnesis.scala
lib/anamnesis/src/core/anamnesis.DataError.scala
lib/anamnesis/src/core/anamnesis.Database.scala
lib/anamnesis/src/core/soundness+anamnesis-core.scala
lib/anamnesis/src/test/anamnesis.Tests.scala
lib/austronesian/src/core/austronesian-core.scala
lib/austronesian/src/core/austronesian.Austronesian.scala
lib/austronesian/src/core/austronesian.Austronesian2.scala
lib/austronesian/src/core/austronesian.StdlibError.scala
lib/austronesian/src/test/austronesian.Tests.scala
lib/imperial/src/core/soundness+imperial-core.scala
lib/rudiments/src/core/soundness+rudiments-core.scala

The new `fuse` method in Rudiments was not exported to `soundness`. It is now.

Remember to export `fuse`

---

lib/larceny/src/plugin/larceny.Subcompiler.scala

Some debugging information was left in the Larceny plugin, which was polluting compiler output when compiling tests. This PR removes it.

Delete some `println`s in Larceny

---

lib/nettlesome/src/core/nettlesome.Service.scala
lib/nettlesome/src/core/soundness+nettlesome-core.scala
lib/scintillate/src/server/scintillate-core.scala
lib/scintillate/src/server/scintillate.HttpServer.scala
lib/scintillate/src/server/scintillate.RequestServable.scala
lib/scintillate/src/server/soundness+scintillate-server.scala

The `Protocolic` typeclass existed, but had no instances, despite being intended for use (at least) with `Http`. An instance has now been created, so it's possible to write:
```scala
tcp"80".serve[Http]:
// handle requests
```

Make `Http` servable

---

build.mill
lib/vexillology/src/core/vexillology.Flags.scala
lib/vexillology/src/test/vexillology.Tests.scala

This introduces an opaque `Flags[E]` type, where `E` is an `Enumerable` value, based on an underlying `Long` value. It can be used to store a set of bits corresponding to each of the enumerable values.

Add a module for working with bit flags

---

lib/telekinesis/src/core/telekinesis.Http.scala

When using `request.parameters.<paramName>`, we check for a contextual `<paramName> is Parameter`. Its value isn't actually used, though it's not marked as `erased`. But this means that an `erased` instance of `Parameter` is not suitable for use.
This makes the `using` value `erased` so that we can make instances of `Parameter` `erased`.

The `Parameter` value for `parameters.<param>` should be `erased`

---

build.mill
lib/fulminate/src/core/fulminate-core.scala
lib/mosquito/src/core/mosquito.Matrix.scala
lib/mosquito/src/core/mosquito.Mosquito.scala
lib/nomenclature/src/core/nomenclature.Nomenclature.scala
lib/nomenclature/src/core/nomenclature.Nomenclature2.scala
lib/panopticon/src/core/panopticon.Panopticon.scala
lib/panopticon/src/test/panopticon.Tests.scala
lib/proscenium/src/core/proscenium-core.scala
lib/proscenium/src/core/soundness+proscenium-core.scala
lib/rudiments/src/core/rudiments-core.scala
lib/rudiments/src/core/soundness+rudiments-core.scala
lib/typonym/src/core/typonym.Typonym.scala
lib/wisteria/src/core/wisteria.ProductDerivationMethods.scala
lib/wisteria/src/core/wisteria.SumDerivationMethods.scala

While constructing a two-tuple is possible with just `(A, B)`, a one-tuple has to be written, `A *: EmptyTuple` and an empty tuple is `EmptyTuple`. We can improve on this with `Mono[A]` and `Zero` respectively.

Alias `EmptyTuple` as `Zero`; `T *: EmtyTuple` as `Mono[T]`

---

lib/nettlesome/src/url/nettlesome.Authority.scala
lib/nettlesome/src/url/nettlesome.Url.scala
lib/nettlesome/src/url/nettlesome.UrlError.scala
lib/nettlesome/src/url/nettlesome.UrlInterpolator.scala

Parsing an HTTP URL can raise either a `UrlError` (to be expected) or a `HostnameError`. This doubles the work required to handle them.
So hereafter, hostname-related errors arising during URL parsing will be encoded in the `UrlError` itself.

Avoid `HostnameError`s when parsing `UrlError`s

---

lib/telekinesis/src/core/telekinesis.Query.scala
lib/wisteria/src/core/wisteria.SumDerivationMethods.scala

A warning in some inlined code suggested that an infinitely recursive `given` had been defined, of the form,
```
given Foo = summonInline[Foo]
```
I didn't check whether this and a couple more examples actually resulted in an infinite recursion, but I replaced them anyway.

Avoid possible occurrences of infinite recursion

---

lib/rudiments/src/core/rudiments-core.scala

Calling `each` on a `Stream` (i.e. a `LazyList`) would do nothing due to its laziness. This is fixed by operating on the `iterator` of the `Iterable` instead.

Iterate using the `iterator` from an `Iterable` in `each` implementation

---

lib/hypotenuse/src/core/hypotenuse-core.scala
lib/hypotenuse/src/core/hypotenuse.Hypotenuse.scala

The methods `successor` and `predecessor` and provided on all floating point types (`Float`, `Double`, `F32` and `F64`) to provide the next and previous values representable by that type, in order. Amongst other things, these will be useful in converting between closed and open intervals on these types.

Provide methods to get adjacent floating-point values

---

build.mill

for every module that extends `RecursivePublishModule` - `publishLocal` command will instead call `publishLocal` command for all of it's moduleDeps that extends `PublishModule` trait. also there is support for `all` module, which will resolve dependencies of it's child modules like web or test.
It doesn't go deeper than that, so that dependencies of modules that extends `PublishModule` are not included.

Recursive module publishing

---

lib/punctuation/src/ansi/punctuation.TextConverter.scala
lib/punctuation/src/core/punctuation.Markdown.scala
lib/punctuation/src/html/punctuation.HtmlConverter.scala

I always found the term `Copy` an ambiguous name for _text_, especially in a programming context. This renames it to `Prose` which is more appropriate and unique.

Rename `Copy` to `Prose`

---

lib/prepositional/src/core/prepositional-core.scala
lib/probably/src/core/probably-core.scala
lib/probably/src/core/probably.Checkable.scala
lib/probably/src/core/soundness+probably-core.scala
lib/turbulence/src/test/turbulence.Tests.scala

This provides a generalized way of comparing values in tests, using `===`. The motivation is to support better syntax for comparing `IArray` elements, but the same mechanism works well for defining tolerance of values. We can now write,
```scala
. assert(_ === array)
```
and it will return true if the elements of the two arrays are the same. And,
```scala
. assert(_ === 100.0 +/- 0.5)
```
to return true for a value that's somewhere between `99.5` and `100.5`.
The latter example could potentially be generalized further to support tolerance of non-`Double` types.

Generalize equivalence of values

---

lib/escapade/src/core/escapade.Ribbon.scala

There was an off-by-one error when rendering a `Ribbon` after refactoring away the use of `curse` (which was removed). The `curse` method was genuinely useful, so a better long-term solution would be helpful.

Fix off-by-one error when rendering ribbons

---

lib/perihelion/src/core/perihelion-core.scala
lib/turbulence/src/core/turbulence-core.scala
lib/turbulence/src/test/turbulence.Tests.scala
lib/zephyrine/src/core/zephyrine.Conduit.scala
lib/zephyrine/src/test/zephyrine.Tests.scala

Make sure that the `shred` method is not only random, but different every time it runs. Previously, the implementation would reuse the same random seed and produce the same sequence every time.

Make shredding random

---

lib/geodesy/src/core/geodesy.Geodesy.scala

Constructing a `Location` west of the Greenwich Meridian wasn't working because negative coordinates (representing "East") were constrained to zero.
This fixes the interpretation.

Fix an issue constructing a `Location` from angles in degrees

---

lib/telekinesis/src/core/telekinesis.Query.scala

A `Parametric` value should never need to be instantiated, so every contextual instance should be erased. But it was being used as a non-erased parameter, which made this impossible. That parameter has now been erased, and it is possible.

Erase usage of `Parametric`

---

lib/contingency/src/core/contingency-core.scala
lib/contingency/src/core/soundness+contingency-core.scala
lib/digression/src/core/digression.Digression.scala
lib/inimitable/src/core/inimitable.Inimitable.scala
lib/kaleidoscope/src/core/kaleidoscope.Kaleidoscope.scala
lib/nettlesome/src/core/nettlesome.EmailAddress.scala
lib/nettlesome/src/core/nettlesome.Hostname.scala
lib/nettlesome/src/core/nettlesome.Nettlesome.scala

"Haltingly" was never a good choice, since it implies "stopping and starting". Abortive has the disadvantage that it seems to relate to the `abort` method, and doesn't. But on balance, it's a better choice.

Rename `haltingly` to `abortive`

---

build.mill
lib/mosquito/src/core/mosquito.Mosquito.scala

This upgrades from Scala 3.6.1 to 3.6.4.
Compile errors had to be fixed in Mosquito. Priority seemed to changed in the opaque context for `Vector` to prefer the `apply` method defined on its underlying type, `Tuple`, to the `apply` method defined in scope. It's not clear why this changed, or what the correct answer should be. But it may have changed elsewhere, too.

Upgrade to Scala 3.6.4

---

build.mill
lib/abacist/src/core/abacist.Abacist2.scala
lib/anthology/src/java/anthology.Javac.scala
lib/anthology/src/scala/anthology.Scalac.scala
lib/cellulose/src/core/cellulose.Character.scala
lib/cellulose/src/core/cellulose.CodlEncoder.scala
lib/cellulose/src/core/cellulose.CodlEncoderDerivation.scala
lib/cellulose/src/core/cellulose.CodlFieldReader.scala
lib/distillate/src/core/distillate.Extractable.scala
lib/ethereal/src/core/ethereal-core.scala
lib/eucalyptus/src/syslog/eucalyptus.Syslog.scala
lib/hallucination/src/core/hallucination.Image.scala
lib/scintillate/src/servlet/scintillate.JavaServlet.scala
lib/telekinesis/src/core/telekinesis.Http.scala
lib/turbulence/src/core/turbulence-core.scala
lib/turbulence/src/core/turbulence.Readable.scala
lib/turbulence/src/core/turbulence.Stdio.scala
lib/turbulence/src/core/turbulence.StreamOutputStream.scala
lib/turbulence/src/core/turbulence.Tap.scala
lib/vacuous/src/core/soundness+vacuous-core.scala
lib/vacuous/src/core/vacuous-core.scala

Several changes were required to get Soundness compiling on the nightly release of Scala 3.7. The most significant was the (hopefully temporary) removal of unused import checking, which crashes the compiler in Serpentine.

Make changes necessary to work on Scala 3.7; but still use 3.6.4

---

lib/panopticon/src/core/panopticon-core.scala
lib/panopticon/src/core/panopticon.Panopticon.scala
lib/panopticon/src/core/soundness+panopticon-core.scala

The `get` and `set` methods on a lens don't take advantage of Scala's syntactic sugar for access and updates. By renaming them to `apply` and `update`, we do.

Rename `get` and `set` to `apply` and `update`

---

lib/chiaroscuro/src/core/chiaroscuro.Contrastable.scala
lib/chiaroscuro/src/core/chiaroscuro.Juxtaposition.scala
lib/hieroglyph/src/core/hieroglyph.Unicode.scala

When Chiaroscuro was used to render a comparison of two strings, previously it would draw a large table showing the diff of the characters, one character per line. This was difficult to read.
Now, the text is printed in rows, highlighted in green and red if there's a difference, or blue if the characters are the same. Nonprinting characters, which may be responsible for a difference, are rendered as printable characters.

Improved text comparisons

---

lib/contingency/src/core/contingency-core.scala
lib/eucalyptus/src/core/eucalyptus-core.scala
lib/hieroglyph/src/core/hieroglyph-core.scala
lib/mercator/src/core/mercator-core.scala

Added some indentation to follow-on lines of `extension` signatures.

Tidy up multiline `extension` methods

---

lib/nomenclature/src/core/nomenclature.Required.scala

Better support for non-empty text values using `Name[Required]`.

Provide a simple way of specifying non-empty `Text` values

---

lib/burdock/src/core/burdock.Bootstrapper.scala
lib/fulminate/src/core/fulminate.Communicable.scala
lib/galilei/src/core/galilei.Dos.scala
lib/galilei/src/core/galilei.Linux.scala
lib/galilei/src/core/galilei.MacOs.scala
lib/galilei/src/core/galilei.Posix.scala
lib/galilei/src/core/galilei.Windows.scala
lib/hellenism/src/core/hellenism.Classpath.scala
lib/nettlesome/src/url/nettlesome.Url.scala
lib/nomenclature/src/core/nomenclature.MustNotEqual.scala
lib/nomenclature/src/core/nomenclature.Nomenclature.scala
lib/nomenclature/src/core/nomenclature.Nomenclature2.scala
lib/nomenclature/src/test/nomenclature.Tests.scala
lib/zeppelin/src/core/zeppelin.ZipFile.scala

Customize the error message when attempting to create a `Name[Required]` from an empty string. This also improves the rendering of empty strings in `Message`s.

Better error messages for nonempty `Name`s

---

lib/rudiments/src/core/rudiments-core.scala

The `mutable` and `immutable` fields on `Array`s and `IArray`s were previously written using pattern matching that had to be marked `@unchecked` to get it to compile without warnings, just to avoid writing a no-op `asInstanceOf`. This resulted in unnecessary code being generated.
The implementations have been simplified to the direct cast using `asInstanceOf`.

Don't do unnecessary pattern matching between `Array`s and `IArray`s

---

build.mill
lib/digression/src/core/digression.StackTrace.scala
lib/escapade/src/core/escapade.Teletypeable.scala
lib/gossamer/src/core/gossamer.Textual.scala
lib/mandible/src/core/mandible-core.scala
lib/mandible/src/core/mandible.Bytecode.scala
lib/mandible/src/core/mandible.Classfile.scala
lib/mandible/src/core/mandible.Mandible.scala
lib/mandible/src/test/mandible.Tests.scala
lib/rudiments/src/core/rudiments-core.scala
lib/symbolism/src/core/symbolism.Multiplicable.scala
lib/symbolism/src/core/symbolism.Zeroic.scala

It's now possible to get the bytecode for arbitrary code. You need to write the code in quotes and pass it as a parameter to the `disassemble` method. Like this:
```scala
val bytecode: Bytecode = disassemble('{ println("Hello world") })
```
This will currently produce output that looks like this:
```
Source        Opcode                                     Stack
╶─────────────────────────────────────────────────────────────────────────────────╴
mandible.Tests.scala:53   ₀    get·static                                 ┃
₃    ldc                                        ┃
₅    invoke·virtual scala.ΞPredef # println()   ┃
₈    get·static                                 ┃
₁₁   a·return                                   ┃
```

Mandible improvements

---

lib/turbulence/src/core/turbulence-core.scala

There was a very high density of errors in just a few lines of the `metronome` implementation, which meant that it had no chance of working. It does now.

Fix several errors with the `metronome` implementation

---

build.mill
lib/cellulose/src/test/cellulose.Tests.scala
lib/escapade/src/test/escapade.Tests.scala
src/test/soundness.Tests.scala

Various changes had been made to Contingency, and not reflected in the Cellulose tests, that made these changes necessary. Many tests still don't pass, but this is a step in the right direction.

Sufficient changes for Cellulose tests to compile again

---

build.mill
lib/harlequin/src/ansi/harlequin-ansi.scala
lib/harlequin/src/core/harlequin.SourceCode.scala
lib/harlequin/src/core/soundness+harlequin-core.scala

These two modules had been forgotten. It was possible to make them both compile with minimal changes.

Compile `ansi` and `md` modules of Harlequin

---

build.mill
lib/cellulose/src/core/cellulose.Codl.scala
lib/cellulose/src/test/cellulose.Tests.scala
lib/harlequin/src/md/harlequin.CommonEmbedding.scala
lib/harlequin/src/md/harlequin.JavaEmbedding.scala
lib/harlequin/src/md/harlequin.ScalaEmbedding.scala
lib/harlequin/src/md/punctuation+harlequin-md.scala
lib/harlequin/src/md/soundness+harlequin-md.scala
lib/honeycomb/src/core/honeycomb-core.scala
lib/honeycomb/src/core/honeycomb.Renderable.scala
lib/legerdemain/src/core/legerdemain-core.scala
lib/legerdemain/src/core/legerdemain.Combobox.scala
lib/legerdemain/src/core/legerdemain.Formulation.scala
lib/punctuation/src/core/punctuation.Markdown.scala
lib/punctuation/src/core/punctuation.Translator.scala
lib/punctuation/src/core/soundness+punctuation-core.scala
lib/punctuation/src/html/punctuation-html.scala
lib/punctuation/src/html/punctuation.Embedding.scala
lib/punctuation/src/html/punctuation.HtmlTranslator.scala
lib/punctuation/src/html/punctuation.Outliner.scala
lib/punctuation/src/html/soundness+punctuation-html.scala
src/test/soundness.Tests.scala

We had three definitions of `html`—one for general `Renderable`s, and two for `Markdown`. These have been unified.

Unify the `html` extension method to use `Renderable`

---

lib/quantitative/src/core/quantitative.Expressible.scala
lib/quantitative/src/core/quantitative.Quantitative2.scala

We can now write,
```scala
def seconds[time <: Measure: Expressible in Seconds[1]](duration: Quantity[time]): Int =
time.express(duration).value.toInt
```

Make it possible to express quantities in different units

---

lib/abacist/src/core/abacist-core.scala
lib/abacist/src/core/abacist.Abacist.scala
lib/abacist/src/core/abacist.Abacist2.scala
lib/abacist/src/core/soundness+abacist-core.scala
lib/abacist/src/test/abacist.Tests.scala
lib/phoenicia/src/core/phoenicia.FontSize.scala
lib/quantitative/src/core/quantitative.Amount.scala
lib/quantitative/src/core/quantitative.Quantitative2.scala
lib/quantitative/src/core/soundness+quantitative-core.scala

This also renames `Measurement` to `Amount`. But more importantly, the method previously called `count` is now called `quanta` which means it no longer conflicts with the _other_ `count` method defined in Gossamer.

Rename `Count` to `Quanta` and related changes

---

lib/adversaria/src/core/adversaria.Adversaria.scala
lib/contingency/src/core/contingency.Contingency.scala
lib/fulminate/src/core/fulminate.Communicable.scala
lib/panopticon/src/core/panopticon.Panopticon.scala
lib/vacuous/src/core/vacuous.Vacuous.scala

We couldn't embed non-`Communicable` things inside `m""` messages, even when a `Showable` exists. Now we can.

Make any value with a `Textualizer` also `Communicable`

---

build.mill
lib/hyperbole/src/core/hyperbole-core.scala
lib/hyperbole/src/core/hyperbole.Expansion.scala
lib/hyperbole/src/core/hyperbole.Hyperbole.scala
lib/hyperbole/src/core/soundness+hyperbole-core.scala
lib/hyperbole/src/test/hyperbole.Tests.scala
lib/mandible/src/core/soundness+mandible-core.scala
lib/mandible/src/test/mandible.Tests.scala

All the extractors defined in `QuotesImpl.scala` are now implemented as `case`s in Hyperbole, and should expand.

Implement all TASTy extractors

---

lib/gesticulate/src/core/gesticulate-core.scala
lib/gesticulate/src/core/gesticulate.Content.scala
lib/gesticulate/src/core/gesticulate.Extensions.scala
lib/gesticulate/src/core/gesticulate.Media.scala
lib/gesticulate/src/core/gesticulate.MediaType.scala
lib/gesticulate/src/core/gesticulate.MediaTypeError.scala
lib/gesticulate/src/core/gesticulate.MultipartError.scala
lib/gesticulate/src/core/soundness+gesticulate-core.scala
lib/gesticulate/src/test/gesticulate.Tests.scala
lib/hallucination/src/core/hallucination.Bmp.scala
lib/hallucination/src/core/hallucination.Gif.scala
lib/hallucination/src/core/hallucination.ImageCodec.scala
lib/hallucination/src/core/hallucination.Jpeg.scala
lib/hallucination/src/core/hallucination.Png.scala
lib/honeycomb/src/core/honeycomb.HtmlAttribute.scala
lib/scintillate/src/server/scintillate.Acceptable.scala
lib/scintillate/src/server/scintillate.Retrievable.scala
lib/telekinesis/src/core/telekinesis.Http.scala
lib/telekinesis/src/core/telekinesis.Postable.scala
lib/telekinesis/src/core/telekinesis.Prefixable.scala
lib/telekinesis/src/core/telekinesis.Servable.scala
lib/telekinesis/src/core/telekinesis.Telekinesis.scala

In a struggle to avoid introducing a name which conflicted with the naming scheme for type parameters, media types were called `Medium`s. But since the naming scheme for type parameters has now changed, we can rename them to `MediaType` without the risk that `MediaType` would be misinterpreted as a type parameter.

Rename `Medium` to `MediaType`

---

lib/contingency/src/core/contingency-core.scala
lib/contingency/src/core/soundness+contingency-core.scala

The `survive` method is like a `map`, but performs the operation _safely_, and automatically compacts the results.
It's more or less equivalent to,
```scala
extension [element](list: List[element])
def survive[result](action: element => result): List[result] =
list.flatMap: element =>
try Some(action(element)) catch case _ => None
```

Implement the `survive` method

---

lib/rudiments/src/core/rudiments-core.scala
lib/rudiments/src/core/soundness+rudiments-core.scala

Define an `intercalate` method on `Iterable`s, like a `mkString` for non-String sequences. Unfortunately, this doesn't currently return a more precise collection type than `Iterable`.

Define `intercalate`

---

etc/publish
lib/austronesian/src/core/austronesian.Austronesian2.scala
lib/dissonance/src/core/dissonance.Evolution.scala
lib/hyperbole/src/core/hyperbole.Hyperbole.scala
lib/mandible/src/core/mandible.Bytecode.scala

Provides a `Printable` instance for `Bytecode`. This should make it more convenient to print output from disassembly in tests.

Make `Bytecode` `Printable`

---

lib/rudiments/src/core/rudiments.Concrete.scala
lib/rudiments/src/core/rudiments.Rudiments.scala

Sometimes we want to check that a type is concrete (i.e. not abstract) because we want to use it in a union with another concrete type, but want to make sure they're distinguishable.
The `: Concrete` type bound will now do this. In combination with `NotGiven[T <:< S]`, where `S` is concrete, we can be sure that T is not a subtype of S, whereas the abstractness of `T` could be used as a loophole.
Todo: write a `Distinct` typeclass so we can say,
```
inline def foo[T: Distinct from Int]
```
for example.
Note that inlining is necessary for this to be useful.

Add `Concrete` type constraint

---

lib/contingency/src/core/contingency-core.scala
lib/contingency/src/core/contingency.AccrueTactic.scala
lib/contingency/src/core/contingency.AmalgamateTactic.scala
lib/contingency/src/core/contingency.AttemptTactic.scala
lib/contingency/src/core/contingency.EitherTactic.scala
lib/contingency/src/core/contingency.EscapeTactic.scala
lib/contingency/src/core/contingency.Foci.scala
lib/contingency/src/core/contingency.HaltTactic.scala
lib/contingency/src/core/contingency.OptionalTactic.scala
lib/contingency/src/core/contingency.Tactic.scala
lib/contingency/src/core/contingency.ThrowTactic.scala
lib/contingency/src/core/contingency.TrackTactic.scala
lib/contingency/src/core/soundness+contingency-core.scala

If we're working in an error context, and we want to assert that there have been no `XyzError`s raised (but not aborted) in a prior step, we can invoke `certify[XyzError]()`. This will abort immediately if there have been.

Introduce `certify` method for checking untainted `Tactic`s

---

lib/harlequin/src/core/harlequin.SourceCode.scala

The tokenizer doesn't seem to disambiguate between `using` or `erased` and identifiers. This rewrites identifiers that are `using` or `erased` as modifiers.

Improve highlighting

---

lib/jacinta/src/core/jacinta.Json.scala

We were missing an encoder for `Map`s. This adds it.

Provide an encoder for `Map`s in JSON

---

lib/harlequin/src/core/harlequin.SourceCode.scala

The `given` keyword was not being highlighted as a keyword in Harlequin. Now it is.

Highlight `given` as a keyword

---

lib/aviation/src/core/aviation.Aviation.scala

Fixes the issue where we were using `ordinal` instead of `numerical` when showing months, so January was "0" rather than "1".

Fix off-by-one error in numerical month rendering

---

lib/harlequin/src/core/harlequin.SourceCode.scala
src/test/soundness.Tests.scala

Something in the Turbulence tests is causing it to sometimes deadlock, apparently, but only in CI. The tests never complete, and have to be manually restarted about 50% of the time.
Initial investigation did not reveal what the problem was, so we're going to disable the Turbulence tests for now.

Stop testing Turbulence

---

.github/workflows/publish.yml

Attempts to publish as a single bundle, instead of multiple files.

Update publish command to publish a single bundle to Sonatype

---

etc/header.txt
lib/mandible/src/core/mandible-core.scala

When `disassemble`ing code, the staging compiler didn't provide a way to compile the code without executing it, so we were executing it. This was usually innocuous, but it was annoying, and at worst, dangerous. Now, we compile it inside a method, `_code`, instead of in the main quoted code, so all we actually run is a method definition, while it still gets compiled to a classfile.

Do not execute code when it's disassembled

---

build.mill
lib/cellulose/src/core/cellulose.CodlEncoder.scala

This makes the necessary changes to get Soundness working on Scala 3.7.
This included:
- tweaking the `CodlEncoder` given priority for the generic case
- avoiding running Scaladoc when publishing

Upgrade to Scala 3.7

---

lib/nomenclature/src/core/nomenclature.Nomenclature.scala

We don't need a `Showable` instance for `Name`s because they're subtypes of `Text`.

Remove unnecessary `Showable`

---

lib/hypotenuse/src/core/hypotenuse.Orderable.scala

This makes `Orderable` a cofunctor. There are still lots of typeclasses that need the same treatment.

Add `contramap` to `Orderable`

---

lib/aviation/src/core/aviation.Aviation2.scala
lib/hypotenuse/src/core/hypotenuse.Hypotenuse.scala

These are provided for numeric types and `Instant`s. There might be some other types for which these would be useful, but I couldn't think of them.

Specify `Min` and `Max` values

---

lib/plutocrat/src/core/plutocrat-core.scala
lib/plutocrat/src/core/soundness+plutocrat-core.scala
lib/spectacular/src/core/spectacular.Showable.scala

This includes the 36 most traded currencies, [according to Wikipedia](https://en.wikipedia.org/wiki/Template:Most_traded_currencies).

Include more currency definitions

---

lib/aviation/src/core/aviation-core.scala
lib/aviation/src/core/aviation.Aviation.scala
lib/aviation/src/core/aviation.Aviation2.scala
lib/aviation/src/core/aviation.LeapSeconds.scala
lib/aviation/src/core/aviation.Moment.scala
lib/aviation/src/core/aviation.Month.scala
lib/aviation/src/core/aviation.Monthstamp.scala
lib/aviation/src/core/aviation.RomanCalendar.scala
lib/aviation/src/core/aviation.Timestamp.scala
lib/aviation/src/core/soundness+aviation-core.scala
lib/aviation/src/test/aviation.Tests.scala
lib/plutocrat/src/core/plutocrat.Currency.scala

Improve the typesafety around years by giving them their own opaque type, `Year`. So methods involving years should now use `Year` instead of `Int`. A `Year` can be converted to an `Int` with its `int` method.
This also develops the concept of a `Monthstamp`, which is the combination of a `Year` and `Month`, while a `Month` remains a named month, in no particular year.

Month and Year improvements

---

build.mill
lib/aviation/src/core/aviation-core.scala
lib/aviation/src/core/aviation.Aviation.scala
lib/aviation/src/core/aviation.Aviation2.scala
lib/aviation/src/core/aviation.Calendar.scala
lib/aviation/src/core/aviation.Clockface.scala
lib/aviation/src/core/aviation.LeapSeconds.scala
lib/aviation/src/core/aviation.Moment.scala
lib/aviation/src/core/aviation.Month.scala
lib/aviation/src/core/aviation.Months.scala
lib/aviation/src/core/aviation.Monthstamp.scala
lib/aviation/src/core/aviation.RomanCalendar.scala
lib/aviation/src/core/aviation.Timestamp.scala
lib/aviation/src/core/aviation.Timezone.scala
lib/aviation/src/core/aviation.Weekday.scala
lib/aviation/src/core/aviation.Weekdays.scala
lib/aviation/src/core/aviation.Years.scala
lib/aviation/src/core/soundness+aviation-core.scala
lib/aviation/src/test/aviation.Tests.scala
lib/quantitative/src/units/quantitative.unitDefinitions.scala
lib/quantitative/src/units/soundness+quantitative-units.scala

This provides some more options for formatting dates and times, and gives the packages shorter names.

More time improvements

---

lib/proscenium/src/core/proscenium-core.scala
lib/proscenium/src/core/soundness+proscenium-core.scala

We were exporting `classOf` from `Predef` in Proscenium. @jackgene discovered, indirectly, that this wasn't working and `java.lang.Object` was always being resolved, rather than the specified type.
It appears that the export is effectively "un-inlined", which means that the type parameter arrives as an abstract type variable, rather than the concrete type it requires. Subsequently, this type variable always erases to `java.lang.Object`, which explains the observed behavior.

Do not export `classOf` because the exported version doesn't work

---

lib/aviation/src/core/aviation.Aviation.scala
lib/aviation/src/test/aviation.Tests.scala

Time literals of the form `7.00.pm` or `11.48.am` will now be checked by a macro to ensure that there are exactly two minute digits. This was checked in a previous version, but started failing when some compiler detail around range positions changed.

Reinstate checking of time literals

---

lib/aviation/src/core/aviation.Aviation2.scala
lib/aviation/src/core/aviation.Clock.scala
lib/aviation/src/core/aviation.Period.scala
lib/aviation/src/core/aviation.Tzdb.scala
lib/aviation/src/test/aviation.Tests.scala
lib/burdock/src/core/burdock.Bootstrapper.scala
lib/telekinesis/src/core/telekinesis-core.scala
lib/telekinesis/src/core/telekinesis.HttpEvent.scala

This should make it possible to use alternative representations that are convertible to `Duration`s.

Use `into` for all `Duration` parameters

---

lib/serpentine/src/core/serpentine.Path.scala
lib/serpentine/src/test/serpentine.Tests.scala

Some operations on `Relative` paths were losing (or worse, not respecting) their `Platform` type parameter. That's now fixed.

Some improvements to the types of relative paths

---

lib/hypotenuse/src/core/hypotenuse-core.scala
lib/hypotenuse/src/core/hypotenuse.Hypotenuse.scala
lib/hypotenuse/src/core/soundness+hypotenuse-core.scala
lib/serpentine/src/core/serpentine.Path.scala
lib/serpentine/src/core/serpentine.Relative.scala
lib/serpentine/src/test/serpentine.Tests.scala
lib/symbolism/src/core/soundness+symbolism-core.scala
lib/symbolism/src/core/symbolism.Quotient.scala

You can now pattern-match on a path:
```scala
path match
case root /: t"path" /: t"to" /: t"somewhere" => // ...
```
Note that we must use `/:` instead of `/` for two reasons: we need right-associativity, or else the matching will work from the wrong end of the path; and, we already have an extension method called `/` which seems to make it impossible to have an extractor object as well.

Path pattern matching

---

lib/austronesian/src/core/austronesian.Austronesian2.scala
lib/austronesian/src/core/austronesian.Restorable.scala
lib/caesura/src/core/caesura.DsvDecodable.scala
lib/capricious/src/core/capricious.Randomizable.scala
lib/capricious/src/core/capricious.Seed.scala
lib/cataclysm/src/core/cataclysm.Cataclysm.scala
lib/chiaroscuro/src/core/chiaroscuro.Contrastable.scala
lib/fulminate/src/core/fulminate-core.scala
lib/fulminate/src/core/fulminate.Message.scala
lib/jacinta/src/core/jacinta.Json.scala
lib/legerdemain/src/core/legerdemain.Query.scala
lib/nomenclature/src/core/nomenclature.Nomenclature2.scala
lib/parasite/src/core/parasite-core.scala
lib/proscenium/src/core/proscenium-core.scala
lib/proscenium/src/core/soundness+proscenium-core.scala
lib/scintillate/src/server/scintillate-core.scala
lib/serpentine/src/core/serpentine.Admissible.scala
lib/serpentine/src/core/serpentine.Path.scala
lib/serpentine/src/core/serpentine.Relative.scala
lib/superlunary/src/core/superlunary.Dispatchable.scala
lib/turbulence/src/core/turbulence-core.scala
lib/vacuous/src/core/vacuous-core.scala
lib/vacuous/src/test/vacuous.Tests.scala
lib/vicarious/src/core/vicarious.Proxy.scala
lib/wisteria/src/core/wisteria.ContextRequirement.scala
lib/wisteria/src/core/wisteria.ProductDerivationMethods.scala
lib/wisteria/src/core/wisteria.SumDerivationMethods.scala

The name `summonInline` is annoyingly long for a method that I'm using so regularly. I've provided it as `infer`.

Provide `summonInline` as `infer`

---

lib/austronesian/src/core/austronesian.Austronesian2.scala
lib/caesura/src/core/caesura.DsvDecodable.scala
lib/chiaroscuro/src/core/chiaroscuro.Contrastable.scala
lib/jacinta/src/core/jacinta.Json.scala
lib/legerdemain/src/core/legerdemain.Query.scala
lib/nomenclature/src/core/nomenclature.Nomenclature2.scala
lib/proscenium/src/core/proscenium-core.scala
lib/proscenium/src/core/soundness+proscenium-core.scala
lib/serpentine/src/core/serpentine.Admissible.scala
lib/superlunary/src/core/superlunary.Dispatchable.scala
lib/turbulence/src/core/turbulence-core.scala
lib/wisteria/src/core/wisteria.ProductDerivationMethods.scala
lib/wisteria/src/core/wisteria.SumDerivationMethods.scala

This further simplifies code which uses `summonInline`.

Provide `provide[T]` as a shortcut for `infer[T].give`

---

build.mill

Austronesian was added as a module, and is a dependency of Superlunary, but it wasn't being published. This adds it to the build.

Remember to include `austronesian-core` in the modules to publish

---

build.mill
lib/zephyrine/src/core/zephyrine.Conduit.scala
lib/zeppelin/src/core/zeppelin.ZipStream.scala

Executable ZIP files contain content before the first entry: the program this is to be run to extract (or execute in some other way) the ZIP file's content. This makes it difficult to stream the entries in such a ZIP file, because there are some bytes at the start, before the first entry.
This scans a ZIP stream to cue zip streaming to the start of the entries before trying to read them.

Skip bytes at the start of executable ZIP files

---

lib/hellenism/src/core/hellenism.Classpath.scala
lib/serpentine/src/core/serpentine.Path.scala
lib/serpentine/src/core/serpentine.Relative.scala
lib/serpentine/src/test/serpentine.Tests.scala

It's now possible to rename `Path`s and `Relative`s to a new `Text` value, with,
```scala
val path2 = path.rename(t"quux")
```
or, to reuse the previous name in the new name, it can be referenced with `prior`, like so:
```scala
val path2 = path.rename(prior+t".bak")
```
Note that `rename` may return an `Optional` if it cannot be statically determined to be a non-root.

Make it possible to rename `Path`s and `Relative`s

---

build.mill
lib/superlunary/src/core/superlunary.Dispatchable.scala

An error with Superlunary became apparent during publishing which had not been caught during a normal CI run. This was because the `superlunary.test` module was omitted from the test build, while it was still being published.
Here, we include it in the build, and also fix the issue that wasn't caught.

Include Superlunary in the tests

---

lib/chiaroscuro/src/core/chiaroscuro.Contrastable.scala
lib/chiaroscuro/src/core/chiaroscuro.Decomposable.scala
lib/chiaroscuro/src/core/chiaroscuro.Juxtaposition.scala
lib/gossamer/src/core/gossamer.Decimalizer.scala

When contrasting one type with another, if no "native" `Contrastable` instance could be found, a `Contrastable` would be created from a `Decomposable` instance—which would be derived. Once going down the "decomposable" route, nested types like sets, doubles or ints (which have native `Contrastable` instances) would always be decomposed, because `Decomposable` derivation does not know anything about `Contrastable`s.
So now we do generic derivation on `Contrastable` instances too so that for every nested type, we first search for a `Contrastable` instance, and only then fall back on its decomposition.

Generically-derive contrasts

---

lib/profanity/src/core/profanity-core.scala
lib/profanity/src/core/soundness+profanity-core.scala

The method for introducing an interactive terminal environment had a name which conflicted with the `terminal` _value_, an interface to the actual terminal introduced by `terminal`. This was unnecessarily confusing. We fix it by renaming the first `terminal` to `interactive`.

Rename `terminal` to `interactive`

---

lib/exoskeleton/src/core/exoskeleton-core.scala
lib/exoskeleton/src/core/soundness+exoskeleton-core.scala

When writing a CLI application, inside the `cli` block, you can't normally do anything that's marked as "effectful" with `(using Effectful)`. That's to save you from doing it by accident.
But sometimes you need to, so the `effectful` block is provided for that purpose.

Provide an `effectful` block which allows side-effects

---

lib/exoskeleton/src/args/exoskeleton.Argument.scala
lib/exoskeleton/src/args/exoskeleton.Suggestion.scala
lib/exoskeleton/src/completions/exoskeleton-completions.scala
lib/exoskeleton/src/completions/exoskeleton.CliCompletion.scala
lib/exoskeleton/src/completions/exoskeleton.Pathname.scala
lib/exoskeleton/src/completions/exoskeleton.TabCompletions.scala
lib/galilei/src/core/galilei-core.scala
lib/serpentine/src/core/serpentine.Relative.scala

ZSH supports completion entries where the text that's on the commandline isn't necessarily included in full in the list of completion options. A typical example would be when calling `foo /home/<tab>` while the completions would be things like `/home/foo` and `/home/bar`, only `foo` and `bar` would be displayed in the list of completion options, because `/home/` would be specified as a "prefix".
For Bash and Fish, nothing changes: the completions are always shown in full.
Upon this, a new `Pathname` extractor has been provided which allows navigation of the filesystem.

Support zsh prefixes

---

lib/escapade/src/core/escapade.Teletype.scala
lib/gossamer/src/core/gossamer-core.scala
lib/gossamer/src/core/gossamer.Gossamer.scala
lib/gossamer/src/core/gossamer.Textual.scala
lib/gossamer/src/core/soundness+gossamer-core.scala
lib/hieroglyph/src/core/hieroglyph-core.scala
lib/hieroglyph/src/core/soundness+hieroglyph-core.scala

`Text` doesn't have a `filter` method, but it was useful to be able to erase certain characters (like whitespace), so I added an `erase` method for now.

Improvements to Gossamer, including `erase` method

---

lib/cellulose/src/core/cellulose.Codl.scala
lib/cellulose/src/core/cellulose.CodlDecoder.scala
lib/cellulose/src/core/cellulose.CodlEncoder.scala

Generic derivation on self-referential types wasn't working because some references to recursive types were strict, which led to deadlock at runtime. (Or a compiletime failure, in some variations.)
That's now fixed, though similar changes still need to be made for several other typeclasses.

Make sure generic derivation works for recursive types

---

build.mill
lib/gossamer/src/core/soundness+gossamer-core.scala
lib/honeycomb/src/core/honeycomb.HtmlAttribute.scala
lib/honeycomb/src/core/honeycomb.html5.scala
lib/nettlesome/src/url/nettlesome.Rfc3986.scala
lib/nettlesome/src/url/soundness+nettlesome-url.scala

We previously had to use `Text` values for paths in HTML, because we didn't have a good representation of paths. The recent updates to Serpentine fix that, and here we provide the typeclasses necessary to allow URL paths to be included in HTML attributes.

Allow absolute and relative links for path-like attributes in HTML

---

lib/chiaroscuro/src/core/chiaroscuro.Decomposable.scala
lib/chiaroscuro/src/core/chiaroscuro.Decomposition.scala
lib/probably/src/core/probably.Probably.scala
lib/punctuation/src/test/punctuation.Tests.scala

Generic derivation for `Decomposable`s was taking a very long time. The problem appeared to be related to the recursive derivation on `Iterable` subtypes. After various attempts to shuffle the order and priority of the implicits, the changes here appear to work as desired.

Decomposition performance

---

lib/parasite/src/core/parasite.Heap.scala

We can now find out a `Memory` value for how much of the heap is allocated, with `Heap.used`.
This is a trivial implementation, but there's scope to add new features to it. It's currently defined in Parasite, but it might be better off in a new module, if it gets expanded.

Provide a means to access heap usage

---

lib/honeycomb/src/core/honeycomb.Renderable.scala
lib/honeycomb/src/core/honeycomb.html5.scala
lib/punctuation/src/html/punctuation.HtmlTranslator.scala

We can now call `stackTrace.html` and get an HTML representation of the stack trace. This probably still requires some more styling, but it's a start.

Render stack traces

---

lib/anticipation/src/log/anticipation.Realm.scala
lib/anticipation/src/text/anticipation.Anticipation.scala
lib/fulminate/src/core/fulminate.TextEscapes.scala
lib/gossamer/src/core/gossamer-core.scala
lib/gossamer/src/core/gossamer.Pue.scala
lib/mercator/src/core/mercator-core.scala
lib/parasite/src/core/parasite-core.scala

We can now make `Text` an `into type`, which means that `Text` parameters everywhere can automatically take `String`s without explicit conversion.
Previously, only a few uses of `Text` in parameter position were marked `into[Text]`, so those have now been removed and the automatic-conversion functionality is applied universally.

Make `Text` an `into` type

---

lib/exoskeleton/src/args/exoskeleton.Discoverable.scala

Tab-completion on a flag whose value is determined by an enumeration should now work out of the box.

Make enumerations discoverable by default

---

.github/workflows/main.yml
lib/exoskeleton/src/rig/exoskeleton-rig.scala
lib/exoskeleton/src/test/exoskeleton.Tests.scala
lib/probably/src/core/probably-core.scala
lib/probably/src/core/probably.Ci.scala

We gave special privilege to Github Actions by giving it its own special method to check if its the host environment. But other CI systems exist, so the `githubActions` method has been moved into the `Ci` object, and several other tests have been added for other CI services.

Generalize CI checks
